doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            taxorepoenum: App\DBAL\TaxoRepoEnumType
            occurrencetypeenum: App\DBAL\OccurrenceTypeEnumType
            inputsourceenum: App\DBAL\InputSourceEnumType
            phenologyenum: App\DBAL\PhenologyEnumType
            certaintyenum: App\DBAL\CertaintyEnumType
            publishedlocationenum: App\DBAL\PublishedLocationEnumType
            locationtypeenum: App\DBAL\LocationTypeEnumType
            taxorestrictiontypeenum: App\DBAL\TaxoRestrictionTypeEnumType
            fielddatatypeenum: App\DBAL\FieldDataTypeEnumType
            languageenum: App\DBAL\LanguageEnumType
            locationaccuracytypeenum: App\DBAL\LocationAccuracyEnumType
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
