# For sortable properties, we must add a keyword type field which MUST 
# follow the following naming convention <propertyname>'_keyword'.
# Cause: "Fielddata is disabled on text fields by default. Set fielddata=true on [userSciName] in order to load fielddata in memory by uninverting the inverted index. 
# *Note that this can however use significant memory*. Alternatively use a keyword field instead. [reason: all shards failed]"   
fos_elastica:
    clients:
        default: { host: '%env(FOS_ELASTICA_CLIENTS_DEFAULT_HOST)%', port: '%env(FOS_ELASTICA_CLIENTS_DEFAULT_PORT)%' }
    indexes:
        occurrences: 
            index_name: '%env(FOS_ELASTICA_INDEXES_OCCURRENCES_INDEX_NAME)%'
            use_alias: true
            settings:
                index:
                    analysis:
                        analyzer:
                            occ_analyzer:
                                type: custom
                                tokenizer: keyword
                                filter: ["asciifolding", "lowercase", "french_stem"]
                        normalizer:
                            occ_normalizer:
                                type: custom
                                filter: ["asciifolding", "lowercase"]
            types:
                occurrence:
                    properties:
                        id:
                            type: "text"
                        id_keyword:
                            type: "integer"
                        geom: 
                            type: "geo_shape"
                        userId: 
                            type: "integer"
                        projectId: 
                            type: "integer"
                        userEmail: ~
                        userPseudo: ~
                        observer: ~
                        observerInstitution: ~
                        # sortable property
                        dateObserved: 
                            type: "date"
                            format: 'yyyy-MM-dd HH:mm:ss'
                        dateObserved_keyword:   
                            type: "keyword" 
                        dateObservedYear:
                            type: "integer"
                        dateObservedMonth:
                            type: "integer"
                        dateObservedDay:
                            type: "integer"
                        dateCreated: 
                            type: "date"
                            format: 'yyyy-MM-dd HH:mm:ss' 
                        dateCreated_keyword: 
                            type: "keyword"
                        dateUpdated: 
                            type: "date"
                            format: 'yyyy-MM-dd HH:mm:ss' 
                        datePublished: 
                            type: "date"
                            format: 'yyyy-MM-dd HH:mm:ss' 
                        # sortable property
                        userSciName: 
                            type: "text"
                        userSciName_keyword:
                            type: "keyword" 
                            normalizer: "occ_normalizer"
                        userSciNameId: 
                            type: "integer"
                        acceptedSciName: ~
                        acceptedSciNameId: 
                            type: "integer"
                        # sortable property
                        family:
                            type: "text"
                        family_keyword:
                            type: "keyword" 
                        plantnetId:
                            type: "integer"
                        taxoRepo:
                            type: "text"
                        # sortable property
                        certainty:
                            type: "text"
                        certainty_keyword:
                            type: "keyword" 
                        occurrenceType: ~
                        isWild: 
                            type: "boolean"
                        phenology: ~
                        sampleHerbarium: 
                            type: "boolean"
                        bibliographySource: ~ 
                        inputSource: ~
                        isPublic: 
                            type: "boolean"
                        isPublic_keyword:   
                            type: "keyword" 
                        isVisibleInCel: 
                            type: "boolean"
                        isVisibleInVegLab: 
                            type: "boolean"
                        signature: ~
                        # sortable property
                        elevation:
                            type: "integer"
                        elevation_keyword:
                            type: "integer"
                        geodatum: ~
                        # sortable property
                        locality:
                            type: "text"
                        locality_keyword:
                            type: "keyword"
                            normalizer: "occ_normalizer"
                        localityInseeCode:
                            type: "text"
                        sublocality: ~
                        environment: ~
                        localityConsistency: ~
                        station: ~
                        publishedLocation: ~
                        locationAccuracy: ~
                        osmCounty: ~
                        osmState: ~
                        osmPostcode: ~
                        osmCountry: ~
                        osmCountryCode: ~
                        osmId: ~
                        osmPlaceId: ~
                        # sortable property
                        identiplanteScore:
                            type: "integer"
                        identiplanteScore_keyword:
                            type: "integer"
                        isIdentiplanteValidated:
                            type: "boolean"
                        tags: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Occurrence
                        provider: ~
                        finder: ~
                            # service: app.elastica.finder.altruist.transformed.finder
                        repository: App\Elastica\Repository\OccurrenceRepository
                        model_to_elastica_transformer:
                            service: app.search.occurrence_to_elastica_transformer
                        # When deleting some entities then reloading, 
                        # elasticsearch sometimes sometimes cries because 
                        # he cannot find the corresponding Doctrine objects 
                        # It happens when the index is queried before deletions 
                        # are not yet effective in the index... 
                        elastica_to_model_transformer:
                            ignore_missing: true

        photos: 
            index_name: '%env(FOS_ELASTICA_INDEXES_PHOTOS_INDEX_NAME)%'
            use_alias: true
            settings:
                index:
                    analysis:
                        analyzer:
                            photo_analyzer:
                                type: custom
                                tokenizer: keyword
                                filter: ["asciifolding", "lowercase", "french_stem"]
                        normalizer:
                            photo_normalizer:
                                type: custom
                                filter: ["asciifolding", "lowercase"]
            types:
                photo:
                    properties:
                        id:
                            type: "text"
                        userId: 
                            type: "integer"
                        userEmail: ~
                        userPseudo: ~
                        originalName: ~
                        # sortable property
                        dateShot: 
                            type: "date"
                            format: 'yyyy-MM-dd HH:mm:ss' 
                        dateShot_keyword:
                            type: "keyword"
                        dateShotYear:
                            type: "integer"
                        dateShotMonth:
                            type: "integer"
                        dateShotDay:
                            type: "integer"
                        dateObserved: 
                            type: "date"
                            format: 'yyyy-MM-dd HH:mm:ss' 
                        dateObservedYear:
                            type: "integer"
                        dateObservedMonth:
                            type: "integer"
                        dateObservedDay:
                            type: "integer"
                        dateCreated: 
                            type: "date"
                            format: 'yyyy-MM-dd HH:mm:ss' 
                        dateCreated_keyword: 
                            type: "keyword"
                        dateUpdated: 
                            type: "date"
                            format: 'yyyy-MM-dd HH:mm:ss' 
                        userSciName: ~
                        userSciNameId: 
                            type: "integer"
                        # sortable property
                        family:
                            type: "text"
                        family_keyword:
                            type: "keyword"
                        # sortable property
                        certainty:
                            type: "text"
                        certainty_keyword:
                            type: "keyword"
                        isPublic: 
                            type: "boolean"
                        # sortable property
                        locality:
                            type: "text"
                        frenchDep:
                            type: "integer"
                        locality_keyword:
                            type: "keyword"
                        osmCounty: ~
                        osmCountry: ~
                        osmCountryCode: ~
                        projectId: 
                            type: "integer"
                        tags: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Photo
                        provider: ~
                        finder: ~
                        repository: App\Elastica\Repository\PhotoRepository
                        model_to_elastica_transformer:
                            service: app.search.photo_to_elastica_transformer
