nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(string:CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-count']
        expose_headers: ['Content-Disposition', 'Content-Length', 'Link', 'X-count']
        max_age: 3600
    paths:
        '^/api/':
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE']
                max_age: 3600
