security:
    providers:
        sso:
            id: App\Security\SSO\SSOUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - App\Security\SSO\SSOAuthenticator

