vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: '%env(PHOTO_URI_PREFIX)%' 
            upload_destination: '%env(BASE_PHOTO_DIR)%' 
            namer: vich_uploader.mappings.media_object.namer
            directory_namer: vich_uploader.mappings.media_object.directory_namer
