# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3-node-browsers
        environment:
          APP_ENV: test
          APP_SECRET: $ecretf0rt3st
          DATABASE_URL: mysql://root:@127.0.0.1:3306/circle_test
          SYMFONY_DEPRECATIONS_HELPER: weak

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      - image: circleci/mysql:5.7-ram

    # branches:
    #   only:
    #     - master

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - composer-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - composer-{{ .Environment.CACHE_VERSION }}-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # prepare the database
      #- run: php bin/console doctrine:migrations:migrate --no-interaction
      #- run: php bin/console doctrine:fixtures:load --no-interaction
      - run: mysql -u root circle_test < ./sql/cel2.sql

      # Cache warmup
      - run: php bin/console cache:clear

      # run tests with phpunit or codecept
      - run: ./bin/phpunit
      # - run: ./vendor/bin/codecept build
      # - run: ./vendor/bin/codecept run

      # upload artifacts
      - store_artifacts:
          path: ./var/log/test.log

