# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # ########################################################################
    # ENTITY (DE)SERIALIZATION
    # ########################################################################

    # Encoder for GeoJSON format:
    'App\Serializer\GeoJsonOccurrenceNormalizer':
        arguments: [ '@api_platform.serializer.normalizer.item' ]
        tags: [ 'serializer.normalizer' ]

    # Serializer for GeoJSON format:
    app.serializer.geo_json_occurrence_encoder:
        class: App\Serializer\GeoJsonOccurrenceEncoder
        tags: [ 'serializer.encoder' ]

    # Encoder for JSON-PATCH format:
    'App\Serializer\JsonPatchOccurrenceNormalizer':
        arguments: [ '@api_platform.serializer.normalizer.item' ]
        tags: [ 'serializer.normalizer' ]

    # Serializer for JSON-PATCH format:
    app.serializer.json_patch_encoder:
        class: App\Serializer\JsonPatchOccurrenceEncoder
        tags: [ 'serializer.encoder' ]

    # Encoder for PDF format:
    'App\Serializer\PdfOccurrenceNormalizer':
        arguments: [ '@api_platform.serializer.normalizer.item' ]
        tags: [ 'serializer.normalizer' ]

    # Serializer for PDF format:
    app.serializer.pdf_occurrence_encoder:
        class: App\Serializer\PdfOccurrenceEncoder
        tags: [ 'serializer.encoder' ]

    # ########################################################################
    # ELASTICA ENTITY TO DOCUMENT TRANSFORMERS
    # ########################################################################
    # Services for transforming entities to elasticsearch documents 
    # ########################################################################
 
    # Occurrence resource type.
    app.search.occurrence_to_elastica_transformer :
        class: App\Search\OccurrenceToElasticaTransformer

    # Photo resource type.
    app.search.photo_to_elastica_transformer :
        class: App\Search\PhotoToElasticaTransformer

    # ########################################################################
    # SECURITY VOTERS (ACL)
    # ########################################################################

    # Security: voter (ACL) for occurrence entities/resources 
    security.acccess.occurrence_voter :
        class:  App\Security\OccurrenceVoter
        public: false
        tags:
            - { name: security.voter }

    # Security: voter (ACL) for photo resources 
    security.acccess.photo_voter :
        class:  App\Security\PhotoVoter
        public: false
        tags:
            - { name: security.voter }

    # Security: voter (ACL) for user profile resources 
    security.access.user_profile_cel_voter :
        class:  App\Security\UserProfileCelVoter
        public: false
        tags:
            - { name: security.voter }

    # Security: voter (ACL) for user profile resources 
    security.access.user_occurrence_tag_voter :
        class:  App\Security\UserOccurrenceTagVoter
        public: false
        tags:
            - { name: security.voter }

    # Security: voter (ACL) for user custom fields resources 
    security.access.user_custom_field_voter :
        class:  App\Security\UserCustomFieldVoter
        public: false
        tags:
            - { name: security.voter }

    # Security: voter (ACL) for user custom fields resources 
    security.access.user_custom_field_occurrence_voter :
        class:  App\Security\UserCustomFieldOccurrenceVoter
        public: false
        tags:
            - { name: security.voter }




    # ########################################################################
    # DOCTRINE ENTITY EVENT LISTENERS
    # ########################################################################

    app.event.listener.occurrence.event.listener:
        class: App\EventListener\OccurrenceEventListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    app.event.listener.photo.event.listener:
        class: App\EventListener\PhotoEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    app.event.listener.owned.entity.event.listener:
        class: App\EventListener\OwnedEntityEventListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    app.event.listener.timestamped.entity.event.listener:
        class: App\EventListener\TimestampedEntityEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    # This is not wired. Thanks to API platform?
    app.event.subscriber.add.photo.url.subscriber:
        class: App\EventSubscriber\AddPhotoUrlSubscriber
        tags:
            - { name: jms_serializer.event_subscriber, event: onPreSerialize }


    # ########################################################################
    # RESPONSE EVENT LISTENERS
    # ########################################################################

    app.event.listener.xcount.response.listener:
        class:      App\EventListener\XcountResponseListener
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    # ########################################################################
    # CUSTOM ELASTICA FINER
    # ########################################################################

    app.elastica.finder.altruist.transformed.finder:
        class:      App\Search\AltruistTransformedFinder
        tags:
           - { name: fos_elastica.finder.class }

    # ########################################################################
    # VALIDATORS
    # ########################################################################

    app.validator.listener.no.duplicate.constraint.validator:
        class: App\Validator\NoDuplicateConstraintValidator
        arguments: ["@doctrine.orm.entity_manager"]


